"""empty message

Revision ID: 57ad913d40ad
Revises: f3bdbd356825
Create Date: 2021-11-07 17:32:28.775538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ad913d40ad'
down_revision = 'f3bdbd356825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vege__review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vege__review')
    # ### end Alembic commands ###
